version: '3'
services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - '27017:27017'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=mongo  
    depends_on:
      - mongo
